version: '2'

services:
  php-nginx:
    build: .
    ports:
      - 31000:80
    volumes:
      - ./files/www/:/app/
      - ../xdebug_script/:/var/www/xdebug_script/
      # - ./xdebug.so:/usr/local/lib/php/extensions/no-debug-non-zts-20170718/xdebug.so
    restart: always
    networks:
      - appg_network_group

networks:
  appg_network_group:
    external:
      name: appg_network_group
